services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    links:
      - redis
    depends_on:
      - redis
    # restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
